### ISSUE TITLE
Access shopping basket to see items

### ISSUE THREAD

**Issue by samhstn** [FAC7/amazon2.0#1]
**Description**
As a customer
I want to be able to see my full shopping basket
so that I can review and change my current items.

**Acceptance criteria**
Going to the shopping basket page shows me the items I've chosen and allows me to make changes to them.

@JMurphyWeb @MyPitit @tas12

**Comment by katbow** [comment]
Acceptance criteria now fulfilled for shopping basket! @JMurphyWeb @MyPitit @tas12
