### ISSUE TITLE
Clicking on an item opens the item view with more information

### ISSUE THREAD

**Issue by katbow** [FAC7/amazon2.0#10]
**Description**
As a customer
I want to be able to click on the item for for more details
so that I can get more information for my decision and add the item to my basket.

**Acceptance Criteria**
Clicking on a single item brings up a separate item page
which shows a description and allows you to add to your cart.

Component Structure:
- [x] Product Page
  - [x] InfoBox
  - [x] BuyProduct
  - [x] Button
  - [x] Description
- [x] Review Section
  - [x] Star Rating
  - [x] Review

**Comment by andrewMacmurray** [comment]
Component Structure:

- [ ] Product Page
  - [ ] InfoBox
  - [ ] BuyProduct
  - [ ] Description
  - [ ] Button

**Comment by eliasmalik** [comment]
#83 also has this feature

**Comment by katbow** [comment]
Item view is completed & integrated
