### ISSUE TITLE
Payment results page should have an escape button/link

### ISSUE THREAD

**Issue by eliasmalik** [FAC7/amazon2.0#126]
Currently we are stuck on the payment results page.

Needs a button to carry on shopping or return home or something. Also no header/footer

**Comment by katbow** [comment]
adding in the header/footer seems like the simplest fix for this for surrree

**Comment by eliasmalik** [comment]
Yeah, can't be arsed with this, closing.

**Comment by katbow** [comment]
it's there anyway now @eliascodes :smirk: :shit: :dash: :fu: :goberserk:
