### ISSUE TITLE
Should be able to rate items

### ISSUE THREAD

**Issue by katbow** [FAC7/amazon2.0#13]
**Description**
As a customer
I want to be able to rate items I've purchased
so that I can help other customers make purchase decisions

**Acceptance Criteria**
When I am in item view I can click on the stars and my rating will be saved
#19 #17 #16

**Comment by andrewMacmurray** [comment]
Should be solved with PR #38 Star Rating component now displays a static rating (for the average rating of a product) and also has a dynamic rating system for the review box (so a user can submit a review and click on the stars to choose their rating) :star: :star2: :sparkles: :smile:

**Comment by izaakrogan** [comment]
Someone should definitely pick this up. It is a great component for learning.

Make each star (or circle maybe) a react component and go from there.

You will want to play around with key={i} when mapping out components from your data.

**Comment by katbow** [comment]
Items can now be rated with a star rating system
