### ISSUE TITLE
Setup Server for different endpoints

### ISSUE THREAD

**Issue by andrewMacmurray** [FAC7/amazon2.0#15]
Need to set up a server that can handle requests:

possible view endpoints: if you have any other suggestions please help out! :smile: 

/
/login
/products
/products/category
/products/category/{product-name}
/basket
/payment
/search

/{params*} --- resource handler
/404 --- page for 'not found'

**Comment by katbow** [comment]
@JackTierney how is this looking now? I think we have all the necessary endpoints, but it would be great if you could review this one!

**Comment by franzmoro** [comment]
As spoken with @andrewMacmurray this issue is probably not relevant anymore. closing.
