### ISSUE TITLE
Should be able to make purchase

### ISSUE THREAD

**Issue by samhstn** [FAC7/amazon2.0#2]
**Description**
As a customer
I want to be able to click on checkout from my basket
so that I can complete the purchase of my items

**Acceptance criteria**
In the basket view when I click checkout, it takes me to a page where I can fill in details to make a purchase.

For @tu6619, @ivanmauricio, @eliascodes and @shouston3

**Comment by katbow** [comment]
Alllll done now no one break it like we accidentally did. It's a gentle beast :hatching_chick:
