### ISSUE TITLE
Setup DB with REDIS

### ISSUE THREAD

**Issue by MyPitit** [FAC7/amazon2.0#20]
**What we need to decide:**
- Data structure 

**What are we going to store in our DB**
- Users / Passwords - #3
- Email - #3
- User details when purchase an item - #2
- Items images - #10
- Items description - #10
- User rating - #16 #13
- Reviews - #19
- Items search - #11
- Categories - #4 

**Resources:**
[Redis](http://redis.io/)

**Comment by franzmoro** [comment]
#65 should now address this
