### ISSUE TITLE
List items in Shopping basket

### ISSUE THREAD

**Issue by jay-meister** [FAC7/amazon2.0#26]
#1 Create a list of items for the shopping basket, taking the data from an array called items

@tas12

**Comment by jay-meister** [comment]
resolved in commit 7b85e35dc19e5879c2c74bcf35988cd1b7238621

Added a table to the basket component. Each row represents an item in the basket and displays item name and image with embedded links.

**Comment by jay-meister** [comment]
Assigning to @oturnermajor for closure

**Comment by otajor** [comment]
@JMurphyWeb I would prefer to close this when you've made a PR to master unless there's a reason to close it now?

**Comment by jay-meister** [comment]
@oturnermajor Yeah sorry im not sure what i should do when resolving an
issue.  No reason to close now

**Comment by katbow** [comment]
Now merged in with master @oturnermajor @JMurphyWeb
