### ISSUE TITLE
Customer should be able to login/register

### ISSUE THREAD

**Issue by samhstn** [FAC7/amazon2.0#3]
**Description**
As a customer
I want to be able to login/register
so that I can view saved items

**Acceptance Criteria**
When I click on 'sign in'
I can sign in with an account I previously created or sign up with a new email

May not need this issue, as we can possibly 'login' with credit card details through payment

**Comment by otajor** [comment]
Hmm I think the product specification has changed such that we aren't using logins - going to put a 'won't fix' on this one? @katbow @andrewMacmurray @MyPitit just confirm I'm not wrong on this and close the issue?

**Comment by katbow** [comment]
Yes I think this is correct @oturnermajor , any other comments @MyPitit @andrewMacmurray ?

**Comment by andrewMacmurray** [comment]
@oturnermajor @katbow yep we can close the issue
