### ISSUE TITLE
Make React components for basket

### ISSUE THREAD

**Issue by katbow** [FAC7/amazon2.0#30]
Components to include for basket are:
- [x] table headers
- [x] Item Container including:
  - [x] quantity 
  - [X]  item image + link
  - [X] product name + link
  - [x] stock
  - [x] delete item
  - [x] price
  - [x] additional information
- [x] Checkout Container including:
  - [x] Total
  - [x] Total quantity
  - [x] Checkout Button

**Comment by otajor** [comment]
This format for the issue is so cool :+1: :smile:

**Comment by katbow** [comment]
Closing as all components have been completed
