### ISSUE TITLE
Star rating and reviews for items 

### ISSUE THREAD

**Issue by otajor** [FAC7/amazon2.0#36]
@andrewMacmurray @eleanorreem 

Check [this commit](https://github.com/FAC7/amazon2.0/pull/31/commits/3401e2da627d90db991fbb7a9a544a79e985a1ad) - have added a rating property and a review property. The rating will be a number 1-5, and the review property will be a JSON stringified array of review objects. Also see [this example data structure](https://github.com/FAC7/amazon2.0/blob/master/dbdatasample.json).

At some point can you integrate the star rating and the reviews into your React component for the ProductPage? Thanks =)
- [x] Star rating
- [x] User reviews

**Comment by katbow** [comment]
@andrewMacmurray @eleanorreem is the review section done now? It appears to be from your commits, but just wanted to double check before closing.

**Comment by franzmoro** [comment]
@katbow & @eleanorreem @andrewMacmurray i think the only thing missing is a re-render of the reviews list after submitting a review

**Comment by otajor** [comment]
Closing as I think all the requirements are met and all the changes merged :+1:
