### ISSUE TITLE
Display a list of different items in a category

### ISSUE THREAD

**Issue by samhstn** [FAC7/amazon2.0#4]
**Description**
As a customer
I want to be able to browse a list of items in a category
so that I can see a range of items to choose from.

**Acceptance Criteria**
When I go to a category I can see a list of items from that category with information on item title and price.

For @eleanorreem, @Virginie-T and @andrewMacmurray @RobStallion

**Comment by katbow** [comment]
@Virginie-T @RobStallion love the carousel! :+1:
