### ISSUE TITLE
Unmount checkout container

### ISSUE THREAD

**Issue by katbow** [FAC7/amazon2.0#40]
If the basket is empty, the checkout container should not be mounted on the page. Should only mount if there are items in the basket, and toggle between mount/unmount based if there are items or not.

**Comment by izaakrogan** [comment]
@katbow a simple way to manage this is from the parent component i.e. 

``` js
Parent {
 render() {
  ...
 { items === 0 ? null : <Child /> }
 ...
 }
}
```

**Comment by katbow** [comment]
Thanks @izaakrogan , I found one solution but it's not quite perfect. I'll try adding that in!
