### ISSUE TITLE
Integrating 'mock' DBs with real DB

### ISSUE THREAD

**Issue by eliasmalik** [FAC7/amazon2.0#54]
There are currently components using mock data to populate their components.

Now that the DB query functions are nearing completion, these components should be integrated with the real DB data. Currently the components are both using their own data-structures, differing from the one stored in the DB. Before integration, we should ensure that the DB is storing all the necessary data that the components will need.

@oturnermajor @franzmoro @JackTierney @RobStallion @JMurphyWeb

**Comment by otajor** [comment]
@franzmoro @JackTierney @RobStallion @JMurphyWeb 
plz see [this wiki page](https://github.com/FAC7/amazon2.0/wiki/Populating-Database) for instructions on how to set up the database and how to query it - in particular have a look at the data structure that you will get back for an individual item and **let us know if there is something missing that you need to be included**. 

At the moment we can still change the data structure for individual items, but this will be more difficult once some components have integrated the data structure as it is now.

**Comment by otajor** [comment]
Closing this - DB seems pretty integrated :+1: :+1:
