### ISSUE TITLE
PRE-COMMIT HOOK :rage: :rage: :rage: :rage: :rage: :rage: 

### ISSUE THREAD

**Issue by eleanorreem** [FAC7/amazon2.0#78]
:rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage:

**Comment by katbow** [comment]
:+1: should make high priority really

**Comment by eleanorreem** [comment]
:rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: 
:rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: 
:rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: 
:rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: 
:rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: :rage1: 
:rage1: :rage1: 
:rage2:
:rage3: 

:rage4:

**Comment by eleanorreem** [comment]
:rage1: :rage1: :rage1:    :rage1:                  :rage1:                  :rage1:                :rage1: :rage1: :rage1:     
:rage1:                             :rage1:                  :rage1:      :rage1:            :rage1:     :rage1: 
:rage1: :rage1:                 :rage1:                  :rage1:      :rage1::rage1::rage1:     :rage1: :rage1: :rage1: 
:rage1:                             :rage1:                  :rage1:      :rage1:            :rage1:                             :rage1: 
:rage1: :rage1: :rage1:     :rage1:  :rage1:    :rage1:      :rage1:             :rage1:    :rage1: :rage1: :rage1:

**Comment by katbow** [comment]
@eleanorreem can I close this or are you still raging?
